# K8sWatch default deployment
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k8swatch

resources:
  # CRDs
  - ../crd/bases
  
  # RBAC
  - ../rbac/agent-clusterrole.yaml
  - ../rbac/aggregator-clusterrole.yaml
  - ../rbac/alertmanager-clusterrole.yaml
  
  # Components
  - ../agent/daemonset.yaml
  - ../aggregator/aggregator.yaml
  - ../alertmanager/alertmanager.yaml

commonLabels:
  app.kubernetes.io/name: k8swatch
  app.kubernetes.io/version: "0.1.0"
  app.kubernetes.io/managed-by: kustomize
